// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kxlqebcjpefqtbwdxdss.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt4bHFlYmNqcGVmcXRid2R4ZHNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3NzU5MTEsImV4cCI6MjA2NTM1MTkxMX0.yCgy6oFmYLpmv-F7P04k43PMMqPD8YQQ1_Hz40YSMAk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);